name: pyirf

channels:
  - default
dependencies:
  - python>=3.6
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - scipy
  - astropy>=4.0.2,<5
  - setuptools
  # tests
  - pytest
  - pytest-cov
  # docs
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    - nbsphinx
    - sphinx_automodapi
    - uproot~=3.0
