name: pyirf

channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - scipy
  - astropy=5
  - setuptools
  - tqdm
  # tests
  - pytest
  - pytest-cov
  # docs
  - numpydoc
  - pytables
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - uproot=4
  - awkward=1
  - gammapy=0.19
  - pip
  - pip:
    - ogadf_schema
